<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DocBook.Notifications.Application\DocBook.Notifications.Application.csproj" />
    <ProjectReference Include="..\..\..\DocBook.Infrastructure\DocBook.Infrastructure.csproj" />
  </ItemGroup>

</Project>
