name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore Day1/RefactorOrders/RefactorOrders.csproj

      - name: Build RefactorOrders
        run: dotnet build Day1/RefactorOrders/RefactorOrders.csproj --no-restore

      - name: Run tests
        run: dotnet test Day1/RefactorOrders/RefactorOrders.Tests/RefactorOrders.Tests.csproj --no-buildśś